#!/bin/sh

[ "$#" -lt 1 ] && exit 1

notify-send 'Download started' "$1"

if yt-dlp --add-metadata --geo-bypass -i "$1" -f bestvideo+bestaudio -o "$HOME/Videos/%(title)s";then
    notify-send 'Download finished' "$1"
else
    notify-send 'Download failed' "$1"
fi
