#!/bin/sh

# thanks prime
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [ $# -gt 1 ];then
    SELECTED=$1
else
    SELECTED=$(find ~/repos ~/.local/src -mindepth 1 -maxdepth 1 -type d | fzf --prompt='repo:')
fi

[ -z "$SELECTED" ] && exit 0

SELECTED_NAME=$(basename "$SELECTED" | tr . _)
TMUX_RUNNING=$(pgrep tmux)

if [ -z "$TMUX_RUNNING" ];then
    tmux new-session -s "$SELECTED_NAME" -c "$SELECTED"
    exit 0
fi

if ! tmux has-session -t "$SELECTED_NAME" 2> /dev/null; then
    tmux new-session -ds "$SELECTED_NAME" -c "$SELECTED"
fi

if [ -z "$TMUX" ];then
    tmux attach-session -t "$SELECTED_NAME"
else
    tmux switch-client -t "$SELECTED_NAME"
fi
