#!/bin/sh

URL=$(cat | grep -Po '(((http|https|ftp|gopher)|mailto)[.:][^ >"\t]*|www\.[-a-z0-9.]+)[^ .,;\t>">\):]' | uniq | fzf --prompt="url:")
[ -z "$URL" ] && exit 0

METHOD=$(printf 'Browser\nVideo\nDownload Video\nPicture\n' | fzf --prompt='method:')

if [ "$METHOD" = 'Video' ];then
    mpv "$URL"
elif [ "$METHOD" = 'Download Video' ];then
    setsid download-video "$URL" >/dev/null 2>/dev/null
elif [ "$METHOD" = 'Browser' ];then
    $BROWSER "$URL"
elif [ "$METHOD" = 'Picture' ];then
    curl -sSL "$URL" | imv -
fi
