#!/bin/sh

[ "$1" == "mute" ] && pactl set-sink-mute @DEFAULT_SINK@ toggle || pactl set-sink-volume @DEFAULT_SINK@ $1

VOLUME="$(get_volume)"

[ "$VOLUME" -gt "130" ] && pactl set-sink-volume @DEFAULT_SINK@ 130% && VOLUME="130"

MUTE="$([ "$(pactl get-sink-mute @DEFAULT_SINK@)" == "Mute: yes" ] && echo '(muted)' || echo '')"
ICON="$([ "$MUTE" == "(muted)" ] && echo "audio-volume-muted-symbolic.svg" || echo "audio-volume-high-symbolic.symbolic.png")"

# notify-send --icon "$ICON" -u low "Volume" "$VOLUME% $MUTE" -h "int:value:$VOLUME" -r 98
notify-send -u low "Volume $VOLUME% $MUTE" -h "int:value:$VOLUME" -r 3 -e
