#!/bin/sh

BACKGROUND_FILE="$XDG_CONFIG_HOME/wall"
WALLPAPER_FOLDER="$HOME/Pictures/Wallpaper"

if [ "$#" -ge 1 ];then
    FILE="$(readlink -f "$1")"
else
    imv -r "$WALLPAPER_FOLDER"
fi
[ -f "$FILE" ] || exit 1

MONITOR="$(hyprctl monitors | awk '/Monitor/ {print $2}' | head -n1)"
[ -z "$MONITOR" ] && exit 1


ln -sf "$FILE" "$BACKGROUND_FILE"
if [ -n "$WAYLAND_DISPLAY" ];then
    hyprctl hyprpaper preload "$FILE"
    hyprctl hyprpaper wallpaper "$MONITOR,$FILE"
elif [ -n "$DISPLAY" ];then
    xwallpaper --zoom "$FILE"
else
    echo "Could not set wallpaper" >&2
fi
