#!/bin/sh

CONFIGURATIONS='general scripts hyprland neovim zsh tmux'

if [ "$1" = "clean" ];then
    stow -v --target="$HOME" --delete ./*/
else
    # shellcheck disable=SC2086
    stow -v --target="$HOME" --restow $CONFIGURATIONS
fi
