#!/bin/sh

EMOJI=$(cat ~/.local/share/scripts/emojis | dmenu -i -l 10 -p "Emoji:" | awk '{print $1}')

if [ "$EMOJI" != "" ];then
	printf "$EMOJI" | xclip -selection clipboard
	notify-send "Copied! $EMOJI"
fi
