#!/bin/sh

mount() {
    DEVS=$(lsblk -nro NAME,MOUNTPOINT| awk '/^[^/]*$/ {print $1}')

    DRIVES=''

    for DEV in $DEVS
    do
        DRIVE=$(udisksctl info -b "/dev/$DEV" | awk '/IdLabel/ {out=$2; for(i=3;i<=NF;i++){out=out" "$i}; print out}')
        if [ "$DRIVE" != "" ];then
            if [ "$DRIVES" = "" ];then
                DRIVES="\"$DRIVE\" /dev/$DEV"
            else
                DRIVES="$DRIVES\n\"$DRIVE\" /dev/$DEV"
            fi
        fi
    done

    if [ "$DRIVES" != "" ];then
        DRIVE=$(echo $DRIVES | dmenu -i)
        [ "$DRIVE" != "" ] && (udisksctl mount -b $(echo "$DRIVE" | awk '{print $NF}') || notify-send -u critical "Mounting drive failed" "$DRIVE")
    else
        notify-send "No mountable drives available"
    fi
}

unmount() {
    DEVS=$(lsblk -nro NAME,MOUNTPOINT | awk '/\// {print $1}')

    DRIVES=''

    for DEV in $DEVS
    do
        DRIVE=$(udisksctl info -b "/dev/$DEV" | awk '/IdLabel/ {out=$2; for(i=3;i<=NF;i++){out=out" "$i}; print out}')
        if [ "$DRIVE" != "" ];then
            if [ "$DRIVES" = "" ];then
                DRIVES="\"$DRIVE\" /dev/$DEV"
            else
                DRIVES="$DRIVES\n\"$DRIVE\" /dev/$DEV"
            fi
        fi
    done

    if [ "$DRIVES" != "" ];then
        DRIVE=$(echo $DRIVES | dmenu -i)
        [ "$DRIVE" != "" ] && (udisksctl unmount -b $(echo "$DRIVE" | awk '{print $NF}') || notify-send -u critical "Unmounting drive failed" "$DRIVE")
    else
        notify-send "No unmountable drives available"
    fi
}

power_off() {
    DEVS=$(lsblk -nro NAME,MOUNTPOINT| awk '/^[^/]*$/ {print $1}')

    DRIVES=''

    for DEV in $DEVS
    do
        DRIVE=$(udisksctl info -b "/dev/$DEV" | awk '/IdLabel/ {out=$2; for(i=3;i<=NF;i++){out=out" "$i}; print out}')
        if [ "$DRIVE" != "" ];then
            if [ "$DRIVES" = "" ];then
                DRIVES="\"$DRIVE\" /dev/$DEV"
            else
                DRIVES="$DRIVES\n\"$DRIVE\" /dev/$DEV"
            fi
        fi
    done

    if [ "$DRIVES" != "" ];then
        DRIVE=$(echo $DRIVES | dmenu -i)
        [ "$DRIVE" != "" ] && (udisksctl power-off -b $(echo "$DRIVE" | awk '{print $NF}') || notify-send -u critical "Powering off drive failed" "$DRIVE")
    else
        notify-send "No drives available to power off"
    fi
}

CHOICE=$(echo "Mount\nUnmount\nPower off" | dmenu -i)

if [ "$CHOICE" = "Mount" ];then
    mount
elif [ "$CHOICE" = "Unmount" ];then
    unmount
elif [ "$CHOICE" = "Power off" ];then
    power_off
fi
