#!/usr/bin/env bash
THEMES="Gruvbox\nNord\nMonokai\nSolarized\nDracula"
THEME=$(printf $THEMES | dmenu -i -F)

SCRIPT_PATH="$(dirname $BASH_SOURCE)"
WALLPAPER_FILE="$XDG_CONFIG_HOME/wall.old"
PALETTE_FILE=""

if [ ! -f $WALLPAPER_FILE ]; then
	WALLPAPER_FILE="$XDG_CONFIG_HOME/wall"
fi
cp "$WALLPAPER_FILE" "$XDG_CONFIG_HOME/wall.old"

if [ "$THEME" == "Gruvbox" ];then
	PALETTE_FILE="$SCRIPT_PATH/palettes/gruvbox.txt"
elif [ "$THEME" == "Nord" ];then
	PALETTE_FILE="$SCRIPT_PATH/palettes/nord.txt"
elif [ "$THEME" == "Monokai" ];then
	PALETTE_FILE="$SCRIPT_PATH/palettes/monokai.txt"
elif [ "$THEME" == "Solarized" ];then
	PALETTE_FILE="$SCRIPT_PATH/palettes/solarized.txt"
elif [ "$THEME" == "Dracula" ];then
	PALETTE_FILE="$SCRIPT_PATH/palettes/dracula.txt"
fi
themizer -o "$XDG_CONFIG_HOME/wall" -i "$XDG_CONFIG_HOME/wall.old" -f png -p "$PALETTE_FILE"
xwallpaper --zoom "$XDG_CONFIG_HOME/wall"
