#!/bin/sh

READ=$(cat)
URLS=$(echo "$READ" | grep -Po '(((http|https|ftp|gopher)|mailto)[.:][^ >"\t]*|www\.[-a-z0-9.]+)[^ .,;\t>">\):]' | uniq)

URL=$(echo "$URLS" | dmenu -i -p "URL:" -l 20)

[ "$URL" != "" ] && METHOD=$(printf 'Default\nVideo\nPicture\nBrave\nVideo Download\n' | dmenu -i -p "Method:")

[ "$METHOD" = "Video" ] && nohup mpv "$URL" >/dev/null 2>/dev/null&
[ "$METHOD" = "Brave" ] && nohup brave "$URL" >/dev/null 2>/dev/null&
[ "$METHOD" = "Video Download" ] && nohup download_video "$URL" >/dev/null 2>/dev/null&
[ "$METHOD" = "Picture" ] && nohup sxiv_web "$URL" >/dev/null 2>/dev/null&
