import = [
	"~/.config/alacritty/themes/kanagawa.toml"
]

[font]
size = 9.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"


[window]
opacity = 0.9
padding = { x = 5, y = 5 }

[env]
TERM = "xterm-256color"
