#!/bin/sh

BACKGROUND_FILE="$XDG_CONFIG_HOME/wall"
WALLPAPER_FOLDER="$HOME/Pictures/Wallpaper"
cp "$(sxiv -t $WALLPAPER_FOLDER -r -o | head -n1)" "$BACKGROUND_FILE" && xwallpaper --zoom "$BACKGROUND_FILE"
